spring:
  datasource:
#    type: com.mysql.cj.jdbc.MysqlDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/weblog?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: XJH9901042832
    hikari: # HikariCP连接池配置,这是SpringBoot2.x默认使用的连接池,它是一个高性能的连接池实现 , 同时，它号称是速度最快的连接池
      minimum-idle: 5 # Hikari连接池中最小空闲连接数。
      maximum-pool-size: 20 # Hikari连接池中允许的最大连接数。默认值为10
      auto-commit: true # Hikari连接池中连接的默认自动提交状态。连接是否自动提交事务。
      idle-timeout: 30000 # Hikari连接池中连接的最大空闲时间，默认为30分钟。超过这个时间会被释放
      pool-name: Weblog-HikariCP  # Hikari连接池的名称
      max-lifetime: 1800000 # Hikari连接在连接池中的最大存活时间，超过这个时间会被强制关闭。
      connection-timeout: 30000  # Hikari连接池中获取连接的超时时间，默认为30秒。
      connection-test-query: select 1 # Hikari连接池中测试连接的查询语句，默认为“select 1”

  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 3000

  security:
    user:
      name: admin
      password: 123456

api:
  limit: false # 是否开启接口限流
