server:
  port: 8088
  max-http-header-size: 2MB

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

jwt:
  # 签发人
  issuer: xiangjiahui
  # 密钥
  secret: 4IaJdbh8IuV9toABjxJlPrxZm6yjgkQjsgwNgOoTyZ4rH5YTaiHCOAYPfWE2gcOcHRuG1joYGAfCYwqn5opUxg==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer

api:
  limit: true # 是否开启接口限流

#minio
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: weblog